categories:
  - title: "🚀 Enhancements"
    label: "enhancement"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "📜 Scalafix Migrations"
    label: "scalafix-migration"
  - title: "📗 Documentation"
    label: "documentation"
  - title: "🧪 Test Improvements"
    label: "testing"
  - title: "🏗️ Build Improvements"
    label: "build"
  - title: "🔧 Refactorings"
    label: "refactoring"
  - title: "🌱 Dependency Updates"
    label: "dependency-update"
exclude-labels:
  - "administration"
  - "repos-update"
template: |
  ## What's changed

  $CHANGES

  ## Contributors to this release

  $CONTRIBUTORS
