language: scala
scala:
  - 2.10.6
  - 2.11.8
jdk: oraclejdk7

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

# GCP credentials for integration test
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_1d86b5bcde73_key -iv $encrypted_1d86b5bcde73_iv -in scripts/data-integration-test-421ab9f796e8.json.enc -out scripts/data-integration-test-421ab9f796e8.json -d;
    fi

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      travis_wait 60 sbt -J-XX:ReservedCodeCacheSize=256m ++$TRAVIS_SCALA_VERSION -Dbigquery.project=data-integration-test -Dbigquery.secret=scripts/data-integration-test-421ab9f796e8.json clean scalastyle coverage test it:test coverageReport coverageAggregate;
    else
      ./scripts/travis.sh;
      travis_wait 60 sbt -J-XX:ReservedCodeCacheSize=256m ++$TRAVIS_SCALA_VERSION -Dbigquery.project=dummy-project clean scalastyle coverage test coverageReport coverageAggregate;
    fi

  # Test REPL
  - ./scripts/it-repl.sh $TRAVIS_SCALA_VERSION

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && grep -q SNAPSHOT version.sbt && sbt ++$TRAVIS_SCALA_VERSION publish"

notifications:
  email:
    - neville@spotify.com
    - rav@spotify.com
    - amartin@spotify.com

before_deploy: sbt ++$TRAVIS_SCALA_VERSION "project scio-repl" clean assembly
deploy:
  provider: releases
  api_key:
    secure: NiV4bqbGd36AvUqZR0HWTyJ2NhH4Lb9dMpw53nLygn+uA8nsyzl9a6f0mNYtNFWztofJ2V8oXG1Iy3a9SOvMXppv/z7vYaFSsepJzDPq4b5mb0iQoVlVYbhbNum36sucvxMaVFp57HjDDa+2wf8pt98Wmi7+aj7xmoEfJouW+Nu+EWjoFQ7fY2QV2Wm6r1/VWFDP8RT1ldtYpNkZA4dxSA3tXUXtcmOW5+CKjJD8/aiQozhZQ5glrmqPl6bD0cxB/Ag74WJWJoSJYT+cHzt5Crvrz+aRmvpbtEQMVOn7m464EBpeJKSariJeuWbie4HiGX+cZwtYJOuChERawIDiN5WANCQM6SkRTFVSOYrtZUC8XFphJUkYiFWTKtuxi5vcbAfXzU9DOgBYZBfSzVL6ezmiqI7G0NUfospjfqSkU2FqdNIonxRnAqbzQN8xEZQ61D2IylQRUVRpAWunsYNUMvVp0eEyPQACWuv0uMO7BHTETniJgymEoyt8pkwf54hhl2/Sgl9eXGeGnmnW/ldQ+1fqhKiZHlwtjsJK0ppXpNwrVgBs+xB/IvBbXcGsJZVbYpVD31pUvjMizNlpxeMeEzMfOU9mK4cx5Vu9m+hFXZTTq1Xl6YMOomrPKbqVaQa5j8US4qpbF2KyoA7DHGQ2pYl32ERMbLVLNShYckHzpPA=
  file_glob: true
  file: "scio-repl/target/scala-*/scio-repl-*.jar"
  skip_cleanup: true
  on:
    scala: 2.11.8
    tags: true

# Sonatype credentials
env:
  global:
  - secure: ptfQvlANdAWkOt7dDWvrHBh4cKVbtbMlZvcelLpdH1xJe1p/bqtKyye6/UC9mN33SIkRpn4DsDKltPlGrwwWEhxBVHelIX4Csmdwxg7Rg+/4G4LTpuiOtjsxh+dsqEBTRGIoF4HI1ioZSbGEetTg8h4RHv8DAyLWAaDZnu8tsTHyo/LJIiejlNQ9ILke8zcJvaNp59O0Vq9IkqtNZLGkR2MF1zNpF/FZYKLcoXJEc9QBkiOBOJYgPlTLXEZnt8oAGYl0XriUtapKUAt6lmHPsJ07UKmiVc6W4Rkj4KRqna3kjv12Cu8EuzTz4Rzw2h3QmyJMfee/AtVvQDNJI4Ww+3rSgdihzEWFe5jM75rxEOMT1HNDK38U/nt8oXQPcoUzOyp8B+IGyP5X1+DeybzQHklPbhllmc+cyowQF/AvGoEt1Urfat87daxHcEt7so0/gdo0QetoRGkVyrGIjD2R99Rond5Ug29HNvoBOFNE6CknogdGXurwC3NhDIxkx5CUUh1jUnx5FoLMq3FEBZqfv/8XRx21fMVG6b46h+aW2TDV56g9okhhYc72pSUCvrzURdE5VD/mgjYgnjPZEP/14zTmISAhiaU8KZQQbFUAXX+MeZwMU2LZqhSis9iN583pXV+JprkbsXZ2XO/tHks1BsemDtp+J9J1lHLJsCZuhRo=
  - secure: t7z18oNvWPGQ3Jimsb94l5eSi3XZUUrt83Cms5vSPiO+OALnbKY4ElLlyeRzWGNwybigZiz3g4dBK/qf3rzUM3Sw+0QDXzEmCOK5r4/jEJYwSErfKxmYl9ezX1xxa4859lQ4K2c+1vZjnCpYcs2sFQ5icljgFICAFnmDOv2tkpcOeF8M/S3an9KIKOA/uAPRvx3/l+JmRtQnS60WNyKB/AwBGWq4dLcPSmadnWmJ9YXrRpOCfWZAJnbBugeyB4z3rhf1trGRKXr/UDU5hryjh0N74cUPgW8HOLmaUfnZST/2kbzZC5C4tzFLWhbt+MMipXRyHs4aJFydsSAgLGhLU6cXQmsqF3oM5M1YwdaJVb8GNruKa+8GcOHmfmy+mqOieI+FRmhHrbz0WGgMRu4fYCqKt5InOuvZR7ToYt8dDpsj4YFc5Xal3kHj+/dUNUvw5I1HkzBeQSuuuGOSOZLXIBN4qk47gcf8pbTp3kQsfaQa7BhxQS7wBN6UFNg+cbjJIHLHxQjHqGSO9eGI5gBKQ3OzNB7rSRrdDU7pXG9/wGx8TeJrZNTP7UsZw8yMBItloQO/3lN5JojogRbrBRCBDe6qB8KE/mmFX6457b31ZyMX5Kl/dsm7JYppftbooal/MHKyWH28Vp1uY1w4VozUM/MqDJzk0nEiiWQMB2iVG4g=
