package com.spotify.scio

import sbt._

object Libraries {
  lazy val algebirdCoreVersion = "0.13.10"
  lazy val algebraVersion = "2.10.0"
  lazy val annoy4sVersion = "0.10.0"
  lazy val annoyVersion = "0.2.6"
  lazy val autoServiceAnnotationsVersion = "1.0.1"
  lazy val autoServiceVersion = "1.0.1"
  lazy val autoValueAnnotationsVersion = "1.8.2"
  lazy val avroCompilerVersion = "1.8.2"
  lazy val avroVersion = "1.8.2"
  lazy val beamVendoredVersion = "0.1"
  lazy val beamVersion = "2.54.0"
  lazy val bigtableClientCoreConfigVersion = "1.28.0"
  lazy val bigtableClientCoreVersion = "1.28.0"
  lazy val breezeVersion = "2.1.0"
  lazy val cassandraAllVersion = "3.11.16"
  lazy val cassandraDriverCoreVersion = "3.11.5"
  lazy val catsKernelVersion = "2.10.0"
  lazy val checkerQualVersion = "3.42.0"
  lazy val chillAlgebirdVersion = "0.10.0"
  lazy val chillJavaVersion = "0.10.0"
  lazy val chillProtobufVersion = "0.10.0"
  lazy val chillVersion = "0.10.0"
  lazy val circeCoreVersion = "0.14.6"
  lazy val circeGenericVersion = "0.14.6"
  lazy val circeParserVersion = "0.14.6"
  lazy val commonsCodecVersion = "1.16.0"
  lazy val commonsCompressVersion = "1.8.1"
  lazy val commonsIoVersion = "2.13.0"
  lazy val commonsLang3Version = "3.9"
  lazy val commonsMath3Version = "3.6.1"
  lazy val datastoreV1ProtoClientVersion = "2.17.1"
  lazy val elasticsearchJava7Version = "7.17.14"
  lazy val elasticsearchJava8Version = "8.12.2"
  lazy val failureaccessVersion = "1.0.1"
  lazy val fansiVersion = "0.4.0"
  lazy val gaxGrpcVersion = "2.39.0"
  lazy val gaxHttpjsonVersion = "2.39.0"
  lazy val gaxVersion = "2.39.0"
  lazy val googleApiClientVersion = "2.2.0"
  lazy val googleApiServicesBigqueryVersion = "v2-rev20230812-2.0.0"
  lazy val googleApiServicesPubsubVersion = "v1-rev20220904-2.0.0"
  lazy val googleAuthLibraryCredentialsVersion = "1.21.0"
  lazy val googleAuthLibraryOauth2HttpVersion = "1.21.0"
  lazy val googleCloudBigquerystorageVersion = "3.0.0"
  lazy val googleCloudBigtableVersion = "2.31.0"
  lazy val googleCloudCoreVersion = "2.29.0"
  lazy val googleCloudSpannerVersion = "6.56.0"
  lazy val googleHttpClientGsonVersion = "1.43.3"
  lazy val googleHttpClientVersion = "1.43.3"
  lazy val googleOauthClientVersion = "1.34.1"
  lazy val grpcApiVersion = "1.60.0"
  lazy val grpcAuthVersion = "1.60.0"
  lazy val grpcGoogleCloudPubsubV1Version = "1.108.0"
  lazy val grpcNettyVersion = "1.60.0"
  lazy val grpcStubVersion = "1.60.0"
  lazy val guavaVersion = "32.1.3-jre"
  lazy val hadoopCommonVersion = "3.2.4"
  lazy val hadoopMapreduceClientCoreVersion = "3.2.4"
  lazy val hamcrestVersion = "2.1"
  lazy val httpasyncclientVersion = "4.1.5"
  lazy val httpclientVersion = "4.5.14"
  lazy val httpcoreVersion = "4.4.16"
  lazy val jacksonAnnotationsVersion = "2.14.1"
  lazy val jacksonCoreVersion = "2.14.2"
  lazy val jacksonDatabindVersion = "2.14.1"
  lazy val jacksonDatatypeJsr310Version = "2.14.1"
  lazy val jacksonModuleScalaVersion = "2.14.1"
  lazy val jakartaJsonApiVersion = "2.1.3"
  lazy val jedisVersion = "4.0.1"
  lazy val jmhCoreVersion = "1.37"
  lazy val jmhGeneratorBytecodeVersion = "1.37"
  lazy val jmhGeneratorReflectionVersion = "1.37"
  lazy val jnaVersion = "5.14.0"
  lazy val jodaTimeVersion = "2.10.10"
  lazy val jsr305Version = "3.0.2"
  lazy val junitVersion = "4.13.2"
  lazy val kantanCodecsVersion = "0.5.3"
  lazy val kantanCsvVersion = "0.7.0"
  lazy val kryoShadedVersion = "4.0.3"
  lazy val log4jOverSlf4jVersion = "1.7.30"
  lazy val magnoliaVersion = "1.1.8"
  lazy val magnolifyAvroVersion = "0.7.0"
  lazy val magnolifyBigtableVersion = "0.7.0"
  lazy val magnolifyDatastoreVersion = "0.7.0"
  lazy val magnolifyGuavaVersion = "0.7.0"
  lazy val magnolifyNeo4jVersion = "0.7.0"
  lazy val magnolifyParquetVersion = "0.7.0"
  lazy val magnolifySharedVersion = "0.7.0"
  lazy val magnolifyTensorflowVersion = "0.7.0"
  lazy val meLyhParquetAvroVersion = "0.4.3"
  lazy val mssqlJdbcVersion = "12.6.1.jre11"
  lazy val mysqlConnectorJVersion = "8.3.0"
  lazy val ndarrayVersion = "0.3.3"
  lazy val neo4jJavaDriverVersion = "4.4.3"
  lazy val nettyHandlerVersion = "4.1.100.Final"
  lazy val parquetAvroVersion = "1.13.1"
  lazy val parquetColumnVersion = "1.13.1"
  lazy val parquetCommonVersion = "1.13.1"
  lazy val parquetHadoopVersion = "1.13.1"
  lazy val pprintVersion = "0.8.1"
  lazy val protoGoogleCloudBigquerystorageV1beta1Version = "0.172.0"
  lazy val protoGoogleCloudBigtableAdminV2Version = "2.31.0"
  lazy val protoGoogleCloudBigtableV2Version = "2.31.0"
  lazy val protoGoogleCloudDatastoreV1Version = "0.109.0"
  lazy val protoGoogleCloudPubsubV1Version = "1.108.0"
  lazy val protobufGenericVersion = "0.2.9"
  lazy val protobufJavaVersion = "3.25.2"
  lazy val scalaCollectionCompatVersion = "2.11.0"
  lazy val scalacticVersion = "3.2.18"
  lazy val scalatestVersion = "3.2.18"
  lazy val shapelessVersion = "2.3.10"
  lazy val slf4jApiVersion = "1.7.32"
  lazy val sparkeyVersion = "3.2.5"
  lazy val tensorflowCoreApiVersion = "0.4.2"
  lazy val utilHadoopVersion = "hadoop2-2.2.16"
  lazy val utilVersion = "2.2.16"
  lazy val voyagerVersion = "2.0.2"
  lazy val zetasketchVersion = "0.1.0"
  lazy val zoltarCoreVersion = "0.6.0"
  lazy val zoltarTensorflowVersion = "0.6.0"

  lazy val AlgebirdCore = "com.twitter" %% "algebird-core" % algebirdCoreVersion
  lazy val Algebra = "org.typelevel" %% "algebra" % algebraVersion
  lazy val Annoy = "com.spotify" % "annoy" % annoyVersion
  lazy val Annoy4s = "net.pishen" %% "annoy4s" % annoy4sVersion
  lazy val AutoService = "com.google.auto.service" % "auto-service" % autoServiceVersion
  lazy val AutoServiceAnnotations = "com.google.auto.service" % "auto-service-annotations" % autoServiceAnnotationsVersion
  lazy val AutoValueAnnotations = "com.google.auto.value" % "auto-value-annotations" % autoValueAnnotationsVersion
  lazy val Avro = "org.apache.avro" % "avro" % avroVersion
  lazy val AvroCompiler = "org.apache.avro" % "avro-compiler" % avroCompilerVersion
  lazy val BeamRunnersCoreConstructionJava = "org.apache.beam" % "beam-runners-core-construction-java" % beamVersion
  lazy val BeamSdksJavaCore = "org.apache.beam" % "beam-sdks-java-core" % beamVersion
  lazy val BeamSdksJavaExtensionsAvro = "org.apache.beam" % "beam-sdks-java-extensions-avro" % beamVersion
  lazy val BeamSdksJavaExtensionsGoogleCloudPlatformCore = "org.apache.beam" % "beam-sdks-java-extensions-google-cloud-platform-core" % beamVersion
  lazy val BeamSdksJavaExtensionsProtobuf = "org.apache.beam" % "beam-sdks-java-extensions-protobuf" % beamVersion
  lazy val BeamSdksJavaExtensionsSketching = "org.apache.beam" % "beam-sdks-java-extensions-sketching" % beamVersion
  lazy val BeamSdksJavaExtensionsSorter = "org.apache.beam" % "beam-sdks-java-extensions-sorter" % beamVersion
  lazy val BeamSdksJavaExtensionsSql = "org.apache.beam" % "beam-sdks-java-extensions-sql" % beamVersion
  lazy val BeamSdksJavaExtensionsZetasketch = "org.apache.beam" % "beam-sdks-java-extensions-zetasketch" % beamVersion
  lazy val BeamSdksJavaIoGoogleCloudPlatform = "org.apache.beam" % "beam-sdks-java-io-google-cloud-platform" % beamVersion
  lazy val BeamSdksJavaIoHadoopCommon = "org.apache.beam" % "beam-sdks-java-io-hadoop-common" % beamVersion
  lazy val BeamSdksJavaIoHadoopFormat = "org.apache.beam" % "beam-sdks-java-io-hadoop-format" % beamVersion
  lazy val BeamSdksJavaIoJdbc = "org.apache.beam" % "beam-sdks-java-io-jdbc" % beamVersion
  lazy val BeamSdksJavaIoNeo4j = "org.apache.beam" % "beam-sdks-java-io-neo4j" % beamVersion
  lazy val BeamSdksJavaIoRedis = "org.apache.beam" % "beam-sdks-java-io-redis" % beamVersion
  lazy val BeamVendorGuava32_1_2Jre = "org.apache.beam" % "beam-vendor-guava-32_1_2-jre" % beamVendoredVersion
  lazy val BigtableClientCore = "com.google.cloud.bigtable" % "bigtable-client-core" % bigtableClientCoreVersion
  lazy val BigtableClientCoreConfig = "com.google.cloud.bigtable" % "bigtable-client-core-config" % bigtableClientCoreConfigVersion
  lazy val Breeze = "org.scalanlp" %% "breeze" % breezeVersion
  lazy val CassandraAll = "org.apache.cassandra" % "cassandra-all" % cassandraAllVersion
  lazy val CassandraDriverCore = "com.datastax.cassandra" % "cassandra-driver-core" % cassandraDriverCoreVersion
  lazy val CatsKernel = "org.typelevel" %% "cats-kernel" % catsKernelVersion
  lazy val CheckerQual = "org.checkerframework" % "checker-qual" % checkerQualVersion
  lazy val Chill = "com.twitter" %% "chill" % chillVersion
  lazy val ChillAlgebird = "com.twitter" %% "chill-algebird" % chillAlgebirdVersion
  lazy val ChillJava = "com.twitter" % "chill-java" % chillJavaVersion
  lazy val ChillProtobuf = "com.twitter" % "chill-protobuf" % chillProtobufVersion
  lazy val CirceCore = "io.circe" %% "circe-core" % circeCoreVersion
  lazy val CirceGeneric = "io.circe" %% "circe-generic" % circeGenericVersion
  lazy val CirceParser = "io.circe" %% "circe-parser" % circeParserVersion
  lazy val CommonsCodec = "commons-codec" % "commons-codec" % commonsCodecVersion
  lazy val CommonsCompress = "org.apache.commons" % "commons-compress" % commonsCompressVersion
  lazy val CommonsIo = "commons-io" % "commons-io" % commonsIoVersion
  lazy val CommonsLang3 = "org.apache.commons" % "commons-lang3" % commonsLang3Version
  lazy val CommonsMath3 = "org.apache.commons" % "commons-math3" % commonsMath3Version
  lazy val DatastoreV1ProtoClient = "com.google.cloud.datastore" % "datastore-v1-proto-client" % datastoreV1ProtoClientVersion
  lazy val ElasticsearchJava7 = "co.elastic.clients" % "elasticsearch-java" % elasticsearchJava7Version
  lazy val ElasticsearchJava8 = "co.elastic.clients" % "elasticsearch-java" % elasticsearchJava8Version
  lazy val Failureaccess = "com.google.guava" % "failureaccess" % failureaccessVersion
  lazy val Fansi = "com.lihaoyi" %% "fansi" % fansiVersion
  lazy val Gax = "com.google.api" % "gax" % gaxVersion
  lazy val GaxGrpc = "com.google.api" % "gax-grpc" % gaxGrpcVersion
  lazy val GaxHttpjson = "com.google.api" % "gax-httpjson" % gaxHttpjsonVersion
  lazy val GoogleApiClient = "com.google.api-client" % "google-api-client" % googleApiClientVersion
  lazy val GoogleApiServicesBigquery = "com.google.apis" % "google-api-services-bigquery" % googleApiServicesBigqueryVersion
  lazy val GoogleApiServicesPubsub = "com.google.apis" % "google-api-services-pubsub" % googleApiServicesPubsubVersion
  lazy val GoogleAuthLibraryCredentials = "com.google.auth" % "google-auth-library-credentials" % googleAuthLibraryCredentialsVersion
  lazy val GoogleAuthLibraryOauth2Http = "com.google.auth" % "google-auth-library-oauth2-http" % googleAuthLibraryOauth2HttpVersion
  lazy val GoogleCloudBigquerystorage = "com.google.cloud" % "google-cloud-bigquerystorage" % googleCloudBigquerystorageVersion
  lazy val GoogleCloudBigtable = "com.google.cloud" % "google-cloud-bigtable" % googleCloudBigtableVersion
  lazy val GoogleCloudCore = "com.google.cloud" % "google-cloud-core" % googleCloudCoreVersion
  lazy val GoogleCloudSpanner = "com.google.cloud" % "google-cloud-spanner" % googleCloudSpannerVersion
  lazy val GoogleHttpClient = "com.google.http-client" % "google-http-client" % googleHttpClientVersion
  lazy val GoogleHttpClientGson = "com.google.http-client" % "google-http-client-gson" % googleHttpClientGsonVersion
  lazy val GoogleOauthClient = "com.google.oauth-client" % "google-oauth-client" % googleOauthClientVersion
  lazy val GrpcApi = "io.grpc" % "grpc-api" % grpcApiVersion
  lazy val GrpcAuth = "io.grpc" % "grpc-auth" % grpcAuthVersion
  lazy val GrpcGoogleCloudPubsubV1 = "com.google.api.grpc" % "grpc-google-cloud-pubsub-v1" % grpcGoogleCloudPubsubV1Version
  lazy val GrpcNetty = "io.grpc" % "grpc-netty" % grpcNettyVersion
  lazy val GrpcStub = "io.grpc" % "grpc-stub" % grpcStubVersion
  lazy val Guava = "com.google.guava" % "guava" % guavaVersion
  lazy val HadoopCommon = "org.apache.hadoop" % "hadoop-common" % hadoopCommonVersion
  lazy val HadoopMapreduceClientCore = "org.apache.hadoop" % "hadoop-mapreduce-client-core" % hadoopMapreduceClientCoreVersion
  lazy val Hamcrest = "org.hamcrest" % "hamcrest" % hamcrestVersion
  lazy val Httpasyncclient = "org.apache.httpcomponents" % "httpasyncclient" % httpasyncclientVersion
  lazy val Httpclient = "org.apache.httpcomponents" % "httpclient" % httpclientVersion
  lazy val Httpcore = "org.apache.httpcomponents" % "httpcore" % httpcoreVersion
  lazy val JacksonAnnotations = "com.fasterxml.jackson.core" % "jackson-annotations" % jacksonAnnotationsVersion
  lazy val JacksonCore = "com.fasterxml.jackson.core" % "jackson-core" % jacksonCoreVersion
  lazy val JacksonDatabind = "com.fasterxml.jackson.core" % "jackson-databind" % jacksonDatabindVersion
  lazy val JacksonDatatypeJsr310 = "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % jacksonDatatypeJsr310Version
  lazy val JacksonModuleScala = "com.fasterxml.jackson.module" %% "jackson-module-scala" % jacksonModuleScalaVersion
  lazy val JakartaJsonApi = "jakarta.json" % "jakarta.json-api" % jakartaJsonApiVersion
  lazy val Jedis = "redis.clients" % "jedis" % jedisVersion
  lazy val JmhCore = "org.openjdk.jmh" % "jmh-core" % jmhCoreVersion
  lazy val JmhGeneratorBytecode = "org.openjdk.jmh" % "jmh-generator-bytecode" % jmhGeneratorBytecodeVersion
  lazy val JmhGeneratorReflection = "org.openjdk.jmh" % "jmh-generator-reflection" % jmhGeneratorReflectionVersion
  lazy val Jna = "net.java.dev.jna" % "jna" % jnaVersion
  lazy val JodaTime = "joda-time" % "joda-time" % jodaTimeVersion
  lazy val Jsr305 = "com.google.code.findbugs" % "jsr305" % jsr305Version
  lazy val Junit = "junit" % "junit" % junitVersion
  lazy val KantanCodecs = "com.nrinaudo" %% "kantan.codecs" % kantanCodecsVersion
  lazy val KantanCsv = "com.nrinaudo" %% "kantan.csv" % kantanCsvVersion
  lazy val KryoShaded = "com.esotericsoftware" % "kryo-shaded" % kryoShadedVersion
  lazy val Log4jOverSlf4j = "org.slf4j" % "log4j-over-slf4j" % log4jOverSlf4jVersion
  lazy val Magnolia = "com.softwaremill.magnolia1_2" %% "magnolia" % magnoliaVersion
  lazy val MagnolifyAvro = "com.spotify" %% "magnolify-avro" % magnolifyAvroVersion
  lazy val MagnolifyBigtable = "com.spotify" %% "magnolify-bigtable" % magnolifyBigtableVersion
  lazy val MagnolifyDatastore = "com.spotify" %% "magnolify-datastore" % magnolifyDatastoreVersion
  lazy val MagnolifyGuava = "com.spotify" %% "magnolify-guava" % magnolifyGuavaVersion
  lazy val MagnolifyNeo4j = "com.spotify" %% "magnolify-neo4j" % magnolifyNeo4jVersion
  lazy val MagnolifyParquet = "com.spotify" %% "magnolify-parquet" % magnolifyParquetVersion
  lazy val MagnolifyShared = "com.spotify" %% "magnolify-shared" % magnolifySharedVersion
  lazy val MagnolifyTensorflow = "com.spotify" %% "magnolify-tensorflow" % magnolifyTensorflowVersion
  lazy val MeLyhParquetAvro = "me.lyh" %% "parquet-avro" % meLyhParquetAvroVersion
  lazy val MssqlJdbc = "com.microsoft.sqlserver" % "mssql-jdbc" % mssqlJdbcVersion
  lazy val MysqlConnectorJ = "com.mysql" % "mysql-connector-j" % mysqlConnectorJVersion
  lazy val Ndarray = "org.tensorflow" % "ndarray" % ndarrayVersion
  lazy val Neo4jJavaDriver = "org.neo4j.driver" % "neo4j-java-driver" % neo4jJavaDriverVersion
  lazy val NettyHandler = "io.netty" % "netty-handler" % nettyHandlerVersion
  lazy val ParquetAvro = "org.apache.parquet" % "parquet-avro" % parquetAvroVersion
  lazy val ParquetColumn = "org.apache.parquet" % "parquet-column" % parquetColumnVersion
  lazy val ParquetCommon = "org.apache.parquet" % "parquet-common" % parquetCommonVersion
  lazy val ParquetHadoop = "org.apache.parquet" % "parquet-hadoop" % parquetHadoopVersion
  lazy val Pprint = "com.lihaoyi" %% "pprint" % pprintVersion
  lazy val ProtoGoogleCloudBigquerystorageV1beta1 = "com.google.api.grpc" % "proto-google-cloud-bigquerystorage-v1beta1" % protoGoogleCloudBigquerystorageV1beta1Version
  lazy val ProtoGoogleCloudBigtableAdminV2 = "com.google.api.grpc" % "proto-google-cloud-bigtable-admin-v2" % protoGoogleCloudBigtableAdminV2Version
  lazy val ProtoGoogleCloudBigtableV2 = "com.google.api.grpc" % "proto-google-cloud-bigtable-v2" % protoGoogleCloudBigtableV2Version
  lazy val ProtoGoogleCloudDatastoreV1 = "com.google.api.grpc" % "proto-google-cloud-datastore-v1" % protoGoogleCloudDatastoreV1Version
  lazy val ProtoGoogleCloudPubsubV1 = "com.google.api.grpc" % "proto-google-cloud-pubsub-v1" % protoGoogleCloudPubsubV1Version
  lazy val ProtobufGeneric = "me.lyh" %% "protobuf-generic" % protobufGenericVersion
  lazy val ProtobufJava = "com.google.protobuf" % "protobuf-java" % protobufJavaVersion
  lazy val ScalaCollectionCompat = "org.scala-lang.modules" %% "scala-collection-compat" % scalaCollectionCompatVersion
  lazy val Scalactic = "org.scalactic" %% "scalactic" % scalacticVersion
  lazy val Scalatest = "org.scalatest" %% "scalatest" % scalatestVersion
  lazy val Shapeless = "com.chuusai" %% "shapeless" % shapelessVersion
  lazy val Slf4jApi = "org.slf4j" % "slf4j-api" % slf4jApiVersion
  lazy val Sparkey = "com.spotify.sparkey" % "sparkey" % sparkeyVersion
  lazy val TensorflowCoreApi = "org.tensorflow" % "tensorflow-core-api" % tensorflowCoreApiVersion
  lazy val Util = "com.google.cloud.bigdataoss" % "util" % utilVersion
  lazy val UtilHadoop = "com.google.cloud.bigdataoss" % "util-hadoop" % utilHadoopVersion
  lazy val Voyager = "com.spotify" % "voyager" % voyagerVersion
  lazy val Zetasketch = "com.google.zetasketch" % "zetasketch" % zetasketchVersion
  lazy val ZoltarCore = "com.spotify" % "zoltar-core" % zoltarCoreVersion
  lazy val ZoltarTensorflow = "com.spotify" % "zoltar-tensorflow" % zoltarTensorflowVersion
}
