/*
 * Copyright 2026 Spotify AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.spotify.scio.util

import org.apache.beam.sdk.harness.JvmInitializer
import org.apache.beam.sdk.options.PipelineOptions
import org.slf4j.LoggerFactory

import java.lang.reflect.{InvocationHandler, InvocationTargetException, Method, Proxy}

import scala.util.Try

/**
 * Runs [[AvroGeneratedTrust.install]] on Beam worker JVMs at startup. Registered with
 * ServiceLoader, so the Beam worker harness picks it up.
 */
class AvroGeneratedTrustInitializer extends JvmInitializer {
  override def onStartup(): Unit = AvroGeneratedTrust.install()
  override def beforeProcessing(options: PipelineOptions): Unit = AvroGeneratedTrust.install()
}

/**
 * Avro 1.12.1+ validates every class it loads by name against `ClassSecurityValidator`, and 1.12.2
 * also rejects generated classes unless their package is listed in
 * `org.apache.avro.SERIALIZABLE_PACKAGES`. [[install]] extends the global validator to trust
 * classes annotated `@org.apache.avro.specific.AvroGenerated`, i.e. records, enums and fixed
 * generated by the avro compiler. Other classes, e.g. reflect records, are still checked by the
 * validator previously in place; trust them with `org.apache.avro.SERIALIZABLE_PACKAGES`.
 *
 * Avro is accessed by reflection, since scio-core doesn't depend on it, and skipped on versions
 * without `ClassSecurityValidator`.
 */
object AvroGeneratedTrust {

  private val logger = LoggerFactory.getLogger(this.getClass)

  private val AvroGenerated = "org.apache.avro.specific.AvroGenerated"

  /**
   * Idempotent. Called when creating a [[com.spotify.scio.ScioContext]], by scio's avro readers and
   * coders, and on Beam worker JVMs by [[AvroGeneratedTrustInitializer]]. Call it before reading
   * avro records by other means, e.g. generated builders creating nested records.
   */
  def install(): Unit = installed

  private def isAvroGenerated(cls: Class[_]): Boolean =
    cls.getAnnotations.exists(_.annotationType().getName == AvroGenerated)

  private lazy val installed: Boolean = Try {
    val validator = Class.forName("org.apache.avro.util.ClassSecurityValidator")
    val predicate =
      Class.forName("org.apache.avro.util.ClassSecurityValidator$ClassSecurityPredicate")
    val previous = validator.getMethod("getGlobal").invoke(null)
    val handler = new InvocationHandler {
      override def invoke(proxy: Any, method: Method, args: Array[AnyRef]): AnyRef =
        method.getName match {
          case "isTrusted" if isAvroGenerated(args(0).asInstanceOf[Class[_]]) =>
            java.lang.Boolean.TRUE
          case "hashCode" if args == null => Int.box(System.identityHashCode(proxy))
          case "equals"                   => Boolean.box(proxy.asInstanceOf[AnyRef] eq args(0))
          case "toString" if args == null => s"AvroGenerated or $previous"
          case _                          =>
            try method.invoke(previous, args: _*)
            catch { case e: InvocationTargetException => throw e.getCause }
        }
    }
    val proxy = Proxy.newProxyInstance(predicate.getClassLoader, Array(predicate), handler)
    validator.getMethod("setGlobal", predicate).invoke(null, proxy)
    logger.info("Avro ClassSecurityValidator extended to trust @AvroGenerated classes")
    true
  }.getOrElse(false)
}
