name: ci

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm-ce-java11@21.0.0
      - run: sbt "; scalafmtCheckAll; scalafmtSbtCheck" "; scalafixEnable; scalafixAll --check"
  scalafix-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm-ce-java11@21.0.0
      - run: "cd scalafix; sbt test"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - graalvm-ce-java8@21.0.0
          - graalvm-ce-java11@21.0.0
        scala:
          - 2.12.13
          - 2.13.5
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm-ce-java11@21.0.0
      - run: |
          sbt coverage test coverageReport
          bash <(curl -s https://codecov.io/bash)
  repl-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v10
      - run: ./scripts/circleci_repl.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
    strategy:
      matrix:
        java:
          - graalvm-ce-java8@21.0.0
          - graalvm-ce-java11@21.0.0
        scala:
          - 2.12.13
          - 2.13.5
  mimaReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} mimaReportBinaryIssues"
    strategy:
      matrix:
        java:
          - graalvm-ce-java8@21.0.0
          - graalvm-ce-java11@21.0.0
        scala:
          - 2.12.13
          - 2.13.5
