name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build documentation
    strategy:
      matrix:
        scala: [ 2.13.3, 2.12.12 ]
        java: [ openjdk@1.8, openjdk@1.11 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v1

      - name: Cache SBT
        uses: coursier/cache-action@v3

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.java }}

      - name: Build documentation
        run: sbt $SBT_OPTS ++${{ matrix.scala }} site/makeSite
        env:
          SBT_OPTS: -Dbigquery.project=dummy-projectX
