name: Validate Site Docs

on:
  pull_request:
    branches: [main]
    paths:
      - 'site/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mdoc:
    name: Run mdoc
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Setup Java (corretto@17)
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17
          cache: sbt

      - name: Run mdoc
        run: sbt site/mdoc
